## 다중분류

In [1]:
from sklearn.datasets import fetch_openml

In [2]:
mnist= fetch_openml('mnist_784', version=1)
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [8]:
X,y= mnist['data'],mnist['target']
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000,]

In [9]:
some_digit=X[0]


In [10]:
from sklearn.svm import SVC
svm_clf= SVC()
svm_clf.fit(X_train, y_train)
svm_clf.predict([some_digit])


array(['5'], dtype=object)

In [11]:
some_digit_scores= svm_clf.decision_function([some_digit])
some_digit_scores

array([[ 1.72501977,  2.72809088,  7.2510018 ,  8.3076379 , -0.31087254,
         9.3132482 ,  1.70975103,  2.76765202,  6.23049537,  4.84771048]])

In [13]:
import numpy as np
np.argmax(some_digit_scores)
svm_clf.classes_
svm_clf.classes_[5]

'5'

In [16]:
# OvR 밥법을 사용하도록 하는 코드인데 돌아가지 않음..
from sklearn.multiclass import OneVsRestClassifier

In [ ]:
ovr_clf=OneVsRestClassifier(SVC())
ovr_clf.fit(X_train, y_train)
ovr_clf_predict([some_digit])


In [ ]:
len(ovr_clf.estimators_)

In [21]:
from sklearn.linear_model import SGDClassifier

In [24]:
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train)
sgd_clf.predict([some_digit])

array(['5'], dtype='<U1')

In [25]:
sgd_clf.decision_function([some_digit])

array([[-1.59953229e+04, -2.88426401e+04, -1.21794609e+04,
         2.80898719e+01, -2.02114333e+04,  4.27630498e+03,
        -3.34213755e+04, -1.63766277e+04, -9.93852409e+03,
        -1.05249490e+04]])

In [29]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf,X_train,y_train,cv=3,scoring='accuracy')

array([0.8857 , 0.87645, 0.88105])

In [30]:
from sklearn.preprocessing import StandardScaler
# 아래의 코드같이 입력 스케일을 조정하는 경우에는 정확도를 더 높힐 수 있다

In [ ]:
scaler= StandardScaler()
X_train_scaled= scaler.fit_transform(X_train.astype(np.float64))
cross_val_score(sgd_clf,X_train_scaled,y_train,cv=3,scoring='accuracy' )